import os
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder

def load_base_data(data_dir=None):
    # Fallback path pointing to your centralized data directory
    if data_dir is None:
        data_dir = "/home/sameer/Documents/jupyter/ml-projects-portfolio/data"
        
    path = os.path.join(data_dir, "abalone.data")
    
    # Dataset doesn't contain a native header row
    columns = [
        "Sex", "Length", "Diameter", "Height", 
        "Whole weight", "Shucked weight", "Viscera weight", 
        "Shell weight", "Rings"
    ]
    
    df = pd.read_csv(path, names=columns).drop_duplicates()
    
    # Calculate physical age directly from physiological rings
    df["Age"] = df["Rings"] + 1.5
    
    # Clean up physical anomalies (zero/negative height is biologically impossible)
    df = df[df["Height"] > 0]
    
    return df

def build_features(df):
    # Avoid modifying the original dataframe reference
    dfc = df.copy()
    
    # Encode categorical variable and drop 'Sex_I' to prevent multi-collinearity
    enc = OneHotEncoder(sparse_output=False).set_output(transform="pandas")
    encoded_sex = enc.fit_transform(dfc[["Sex"]])
    
    dfc = pd.concat([dfc, encoded_sex], axis=1)
    dfc = dfc.drop(columns=["Sex", "Sex_I", "Rings"])
    
    # Geometrical approximation features
    dfc["Volume"] = dfc["Length"] * dfc["Diameter"] * dfc["Height"]
    dfc["Density"] = dfc["Whole weight"] / dfc["Volume"]
    
    # Anatomical weight ratios
    dfc["Meat_ratio"] = dfc["Shucked weight"] / dfc["Whole weight"]
    dfc["Shell_ratio"] = dfc["Shell weight"] / dfc["Whole weight"]
    
    # Handle mathematical anomalies generated by division steps
    dfc = dfc.replace([np.inf, -np.inf], np.nan).dropna()
    
    X = dfc.drop(columns=["Age"])
    y = dfc["Age"]
    
    return X, y